name: AVR make
description: Build avr based project with avr toolchain
author: Denis Bazhenov <dotsid@gmail.com>
branding:
  icon: terminal
  color: black
runs:
  using: docker
  image: docker://lpodkalicki/avr-toolchain
  entrypoint: make